### PR TITLE
Hero description styles

### LINKED ISSUE #686: Styles of the hero moment description
### Steps to reproduce the problem
Go to new redesign home page

### What is the current behavior?
Screen Shot 2020-06-23 at 11 53 03

### What is the expected behavior?
- Color text should be $gray-60
- Block description width should be a little bit smaller

Screen Shot 2020-06-23 at 11 53 19

### PR DESCRIPTION
**Pull request by y4izus**
Fix #686

### CODE REVIEW

File: components/landing/TheHeroMoment.vue [hunk 1]
```diff
@@ -90,16 +90,18 @@ export default class extends Vue {
 
   &__description {
     @include type-style('body-long-01');
-    color: $white-text-01;
+    color: $gray-60;
+    max-width: 4.75 * $column-size-large;
```
Comment (delapuente) [inline components/landing/TheHeroMoment.vue:94]: Regarding `max-width`, I'd prefer if we use some multiple of `$column-size-large`. I'd say it is not 6 but can you confirm what's the correct value with @JRussellHuffman, please?

Comment (y4izus) [reply components/landing/TheHeroMoment.vue:94]: Yes, he thinks it looks better with 5 columns, I will change it
