### PR TITLE
Fixes "what qiskit can do" description syles

### LINKED ISSUE #687: Styles of the "what qiskit can do" description
### Steps to reproduce the problem
Go to new redesign home page

### What is the current behavior?
Screen Shot 2020-06-23 at 12 00 05

### What is the expected behavior?
- Color text should be $gray-60
- Block description width should be a little bit bigger

Screen Shot 2020-06-23 at 12 00 25

### PR DESCRIPTION
**Pull request by y4izus**
Fix #687

### CODE REVIEW

File: pages/index.vue [hunk 1]
```diff
@@ -171,7 +171,8 @@ export default class extends QiskitPage {
 
   &__paragraph {
     @include type-style('body-long-01');
-    max-width: 6 * $column-size-large;
+    color: $gray-60;
+    max-width: 6.25 * $column-size-large;
```
Comment (delapuente) [inline pages/index.vue:175]: Please, revert it to 6. This is the size for the paragraphs in the landing page (for large size) as agreed per offline conversations.
