### PR TITLE
fix issue 1039

### LINKED ISSUE #1039: Too much space between the header and content on the metal page
### Steps to reproduce the problem
Go to https://qiskit.org/metal

### What is the current behavior?
Too much space between the header section and the section that says "Early access for quantum..."

### What is the expected behavior?
Close the space between the two section. I recommend 72 px spacing. 

fyi:
@delapuente @y4izus @techtolentino

### PR DESCRIPTION
**Pull request by korgan00**
fix #1039

### CODE REVIEW

File: components/metal/IntroSection.vue [hunk 1]
```diff
@@ -54,6 +64,7 @@ export default class extends Vue {
 
   &__title {
     @include type-style('expressive-heading-05');
+    max-width: 500px;
```
Comment (techtolentino) [inline components/metal/IntroSection.vue:67]: For the sake of sticking with Carbon mini-units (8px), can we use a value here that's a multiple of 8?

`512px`, for example, or `32rem`?

Comment (techtolentino) [reply components/metal/IntroSection.vue:67]: I realize that we have values around the code base that don't stick to this mini-unit principle all the time, but it'd be nice to use it when we can.


thoughts? 

or does this not make sense to do?

**Review by techtolentino — APPROVED** [review]
This is looks great, @korgan00 - just had a question for discussion but I approve what I see here.


Thanks

File: components/metal/IntroSection.vue (hunk 1 above)
Comment (y4izus) [reply components/metal/IntroSection.vue]: If a value doesn't stick to the mini-unit principle is because it was done before we started using the carbon design system. Now we try to use them

File: components/metal/IntroSection.vue [hunk 2]
```diff
@@ -54,6 +64,7 @@ export default class extends Vue {
 
   &__title {
     @include type-style('expressive-heading-05');
+    max-width: 32rem;
```
Comment (y4izus) [inline components/metal/IntroSection.vue:67]: For `max-width` property we are using the columns size variable for each screen. Look the example on line 87: `max-width: 6 * $column-size-large;`. Could you change this `32rem` with the proper value using `$column-size-large;`?

**Review by y4izus — CHANGES_REQUESTED** [review]
Thank you! Just two things:
- The comment I added 👇 
- The build is failing and we can't merge until it's fixed. Please, run `npm run lint` to see the error. I think you can fix it by running: `npm run fix-lint`

**Review by y4izus — APPROVED** [review]
Thank you! :D
