### PR TITLE
fix(code-cell): horizontal content overflow

### LINKED ISSUE #3039: Bug: homepage code block overflow causing issues on mobile
### Steps to reproduce the problem

1. using a mobile device
2. Go to qiskit.org
3. Scroll down to the **What Can Qiskit Do** section
4. See error with the code block

### What is the current behavior?

The code block has an overflow issue due to long lines of code

### What is the expected behavior?

The lines should break so that the entire page doesn't have responsive issues

### Screenshots

localhost_3000_(iPhone 12 Pro)

### Device

_No response_

### OS

_No response_

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eddybrando**
## Changes

This PR fixes the issue with the content of the code cell on the homepage overflowing on small viewports horizontally.

Closes #3039

## Implementation details

Set the `overflow-x` attribute to `scroll`.

## How to read this PR

Grab a coffee because it might take a while.

1. See the 1 line code change
2. Check that it works in the UI

## Screenshots

Screenshot 2023-03-21 at 14 14 36

### CODE REVIEW

File: components/landing/TheQiskitCapabilitiesSection/CodeCell.vue [hunk 1]
```diff
@@ -44,6 +44,7 @@ export default class CodeCell extends Vue {
   display: block;
   background-color: $background-color-lighter;
   color: $text-color;
+  overflow-x: scroll;
```
Comment (techtolentino) [inline components/landing/TheQiskitCapabilitiesSection/CodeCell.vue:47]: Awesome thanks @eddybrando 

👏🏼

**Review by techtolentino — APPROVED** [review]
