### PR TITLE
fix(card): update layout with card tags row

### LINKED ISSUE #2852: Bug: App Card labels overlap title
### Steps to reproduce the problem

1. Go to the [Ecosystem page](https://qiskit.org/ecosystem)
2. Scroll down to the bottom and find `QuantumCircuits.jl`
4. On desktop, see how the labels almost collide with the title 

### What is the current behavior?

On desktop, see how the labels almost collide with the title 

### What is the expected behavior?

It'd be an improvement if the title showed fully, with spacing, while the labels wrapped to the next line

### Screenshots

Screen Shot 2022-10-19 at 8 01 30 AM

### Browser

desktop

### Additional information

**Initially seen on LinkedIn**
Screen Shot 2022-10-19 at 7 57 08 AM

### PR DESCRIPTION
**Pull request by techtolentino**
## Changes

Fixes #2852 
Co-authored by @mariacloehb 

## Implementation details

- moves all tags to its own row, below the title
- removes custom purple tag background, and uses the default Carbon color

## Preview link
- [Ecosystem cards](https://qiskit-org-pr-3442.dcq4xc5i083.us-south.codeengine.appdomain.cloud/ecosystem)
- [Event cards](https://qiskit-org-pr-3442.dcq4xc5i083.us-south.codeengine.appdomain.cloud/events)
- [Advocate cards](https://qiskit-org-pr-3442.dcq4xc5i083.us-south.codeengine.appdomain.cloud/advocates)

## Screenshots

https://github.com/Qiskit/qiskit.org/assets/6276074/0f489c32-e1bd-4de4-b3f1-b8b7d85bef90

### CODE REVIEW

File: components/Ui/UiCard.vue [hunk 1]
```diff
@@ -32,21 +32,21 @@
...
-            <bx-tag
-              v-for="tag in tags"
-              :key="tag"
-              class="card__tag"
-              type="purple"
-            >
-              {{ tag }}
-            </bx-tag>
+          <div class="card__tags">
+            <template v-if="hasTags(tags)">
```
Comment (y4izus) [inline components/Ui/UiCard.vue:36]: If you add this check here, when you have a primary tag and not secondary tags, you will see no tags. For advocates cards is working because instead of passing the primary tag as `primaryTag`, we pass it as `tags` (what is wrong).

File: components/Ui/UiCard.vue [hunk 2]
```diff
@@ -32,21 +32,21 @@
...
+              <bx-tag v-if="primaryTag" class="card__tag" type="purple">
+                {{ primaryTag }}
+              </bx-tag>
+              <bx-tag
+                v-for="tag in tags"
```
Comment (y4izus) [inline components/Ui/UiCard.vue:41]: I suggest to rename `tags` to `secondaryTags` to avoid confusion

**Review by y4izus — CHANGES_REQUESTED** [review]
Thank you Randy! I've 2 comments and a third one I'm asking on our channel because I'm not sure if it's an error or not

File: components/Ui/UiCard.vue (hunk 1 above)
Comment (techtolentino) [reply components/Ui/UiCard.vue]: Updated in https://github.com/Qiskit/qiskit.org/pull/3442/commits/a1c9db3717e90bdfee51def9905d8adc7bca823e

File: components/Ui/UiCard.vue (hunk 2 above)
Comment (techtolentino) [reply components/Ui/UiCard.vue]: Updated in https://github.com/Qiskit/qiskit.org/pull/3442/commits/a1c9db3717e90bdfee51def9905d8adc7bca823e

File: components/Advocates/MeetTheAdvocates/AdvocatesMeetTheAdvocatesCard.vue [hunk 3]
```diff
@@ -3,7 +3,7 @@
     class="advocates-meet-the-advocates-card"
     :image="image"
     :title="name"
-    :tags="formattedRegion"
+    :primary-tag="formattedRegion"
```
Comment (y4izus) [inline components/Advocates/MeetTheAdvocates/AdvocatesMeetTheAdvocatesCard.vue:6]: I think we can continue having this as an array, we are not sure if we can have a list of `primary-tags` in the future

File: components/Advocates/MeetTheAdvocates/AdvocatesMeetTheAdvocatesCard.vue [hunk 4]
```diff
@@ -44,8 +44,7 @@ const props = withDefaults(defineProps<Props>(), {
   slackUsername: "",
 });
 
-// Tags on AppCard is an Array
-const formattedRegion = computed(() => (props.region ? [props.region] : []));
+const formattedRegion = computed(() => (props.region ? props.region : ""));
```
Comment (y4izus) [inline components/Advocates/MeetTheAdvocates/AdvocatesMeetTheAdvocatesCard.vue:47]: Same, keep using the array, please

File: components/Events/EventsCard.vue [hunk 5]
```diff
@@ -3,7 +3,8 @@
     class="events-card"
     :image="image"
     :title="title"
-    :tags="types"
+    :primary-tag="regions[0]"
```
Comment (y4izus) [inline components/Events/EventsCard.vue:6]:
```suggestion
    :primary-tags="regions"
```

File: components/Ui/UiCard.vue [hunk 6]
```diff
@@ -187,30 +182,31 @@ function hasTags(tags: string[]) {
...
-    }
   }
 
   &__tag {
-    white-space: nowrap;
+    margin-right: carbon.$spacing-03;
+    background-color: qiskit.$tag-background-color;
+    color: qiskit.$tag-text-color;
+
+    &:first-child {
```
Comment (y4izus) [inline components/Ui/UiCard.vue:197]: Instead of styling with first child, we can have the modifier `__tag_primary` and give styles with that. In the future, if we have more than one primary tag, we won't have to modify more things

**Review by y4izus — CHANGES_REQUESTED** [review]
Thank you!! please, review my comments :D

File: components/Ui/UiCard.vue [hunk 7]
```diff
@@ -32,21 +32,16 @@
...
-              {{ tag }}
+          <div class="card__tags">
+            <bx-tag v-if="primaryTag" class="card__tag">
+              {{ primaryTag }}
             </bx-tag>
+            <template v-if="hasTags(secondaryTags)">
+              <bx-tag v-for="tag in secondaryTags" :key="tag" type="purple">
+                {{ tag }}
+              </bx-tag>
+            </template>
```
[the remark this answers is not in the document]
Comment (techtolentino) [reply components/Ui/UiCard.vue:43]: This violates [this eslint rule](https://eslint.vuejs.org/rules/no-use-v-if-with-v-for.html#vue-no-use-v-if-with-v-for:~:text=This%20rule%20is%20aimed%20at%20preventing%20the%20use%20of%20v%2Dfor%20directives%20together%20with%20v%2Dif%20directives%20on%20the%20same%20element.):
Screenshot 2023-07-24 at 5 44 07 AM


Moving the iteration to the wrapping <template> element, is also in our code base [here](https://github.com/Qiskit/qiskit.org/blob/main/components/Home/Providers/HomeProvidersList.vue#L4)

But if you'd rather

File: components/Ui/UiCard.vue (hunk 6 above)
Comment (techtolentino) [reply components/Ui/UiCard.vue]: I ended up using the `__tag_primary` modifier, which I needed to style the colors (background purple w/ white text)

However, we still need this first-child selector to properly align the tag the most left tag wit the title above, and text below

File: components/Events/EventsCard.vue (hunk 5 above)
Comment (techtolentino) [reply components/Events/EventsCard.vue]: updated here https://github.com/Qiskit/qiskit.org/pull/3442/commits/80a62b8e218f9e1fc38748f1d4625a9cf8fe141d

File: components/Advocates/MeetTheAdvocates/AdvocatesMeetTheAdvocatesCard.vue (hunk 4 above)
Comment (techtolentino) [reply components/Advocates/MeetTheAdvocates/AdvocatesMeetTheAdvocatesCard.vue]: updated here https://github.com/Qiskit/qiskit.org/pull/3442/commits/80a62b8e218f9e1fc38748f1d4625a9cf8fe141d

File: components/Advocates/MeetTheAdvocates/AdvocatesMeetTheAdvocatesCard.vue (hunk 3 above)
Comment (techtolentino) [reply components/Advocates/MeetTheAdvocates/AdvocatesMeetTheAdvocatesCard.vue]: updated here https://github.com/Qiskit/qiskit.org/pull/3442/commits/80a62b8e218f9e1fc38748f1d4625a9cf8fe141d

File: components/Ui/UiCard.vue (hunk 6 above)
Comment (techtolentino) [reply components/Ui/UiCard.vue]: Wait, I'm realizing this still needs an update... 

Why?
Because if there are no `primary-tags`, but there are `secondary-tags`, the left-margin still needs to be accounted for...

Comment (techtolentino) [reply components/Ui/UiCard.vue]: addressed in [this commit](https://github.com/Qiskit/qiskit.org/pull/3442/commits/63d807865cd33ca4de306f89a3a0ea786ebb7ede)

**Review by y4izus — CHANGES_REQUESTED** [review]
Just 3 more changes and we can merge! 💪 

Apart of what I said on the code, we have this other one. Tags on small devices doesn't look very well
Captura de pantalla 2023-07-25 a las 12 07 23

**Comment by techtolentino** [comment]
> fc7ed60

Addressed in https://github.com/Qiskit/qiskit.org/pull/3442/commits/fc7ed608678f1f96071c631c2621e04df8cbbb7a

**Review by y4izus — APPROVED** [review]
Awesome! Thank you!
