### PR TITLE
ISSUE-426 Fix video background in events page

### LINKED ISSUE #426: Add async video to events index page's background
This issue is related to #381 and #383

Make background video to load always asynchronous to not affect our web performance, force autoplay and prevent the whole video's header from rendering at all when the user is loading the page from a mobile device.

### PR DESCRIPTION
**Pull request by marinaaisa**
Closes #426 

Make background video to load always asynchronous to not affect our web performance, force autoplay and prevent the whole video's header from rendering at all when the user is loading the page from a mobile device.

### CODE REVIEW

File: pages/events/index.vue [hunk 1]
```diff
@@ -31,19 +31,32 @@ import QiskitPage from '~/components/qiskit/QiskitPage.vue'
...
+      video.load()
+      video.muted = true
+      video.play()
     }, 1)
   }
 
-  created () {
-    this.autoplayVideo()
+  get isDesktop () {
+    return this.windowWidth > 600
```
Comment (delapuente) [inline pages/events/index.vue]: Why not using `window.innerWidth` directly?

File: pages/events/index.vue [hunk 2]
```diff
@@ -31,19 +31,32 @@ import QiskitPage from '~/components/qiskit/QiskitPage.vue'
...
     setTimeout(() => {
-      if (this.$refs.video) {
-        this.$refs.video.load()
-        this.$refs.video.muted = true
-        this.$refs.video.play()
-      }
+      video.load()
+      video.muted = true
+      video.play()
     }, 1)
```
Comment (delapuente) [inline pages/events/index.vue]: You don't need to make this process "async" since it is already being used in an async way in the `mounted()` function when called after `nextTick()`.

File: pages/events/index.vue [hunk 3]
```diff
@@ -31,19 +31,32 @@ import QiskitPage from '~/components/qiskit/QiskitPage.vue'
...
-  created () {
-    this.autoplayVideo()
+  get isDesktop () {
+    return this.windowWidth > 600
+  }
+
+  mounted () {
+    this.windowWidth = window.innerWidth
+
+    this.$nextTick(() => {
```
Comment (delapuente) [inline pages/events/index.vue]: You can replace this code with:
```js
await this.$nextTick()
this.autoPlay()
```
You will need to prefix `async` to the function name.

File: pages/events/index.vue (hunk 1 above)
Comment (marinaaisa) [reply pages/events/index.vue]: Because I couldn't access `window` in a computed property directly. It's only available in the `mounted` object.

File: pages/events/index.vue (hunk 3 above)
Comment (marinaaisa) [reply pages/events/index.vue]: Done 👍

File: pages/events/index.vue (hunk 2 above)
Comment (marinaaisa) [reply pages/events/index.vue]: Done 👍  Thanks!

File: pages/events/index.vue [hunk 4]
```diff
@@ -1,6 +1,6 @@
 <template>
   <main>
-    <header class="header-video">
+    <header v-if="isDesktop" class="header-video">
       <video
         ref="video"
```
[the remark this answers is not in the document]
Comment (marinaaisa) [reply pages/events/index.vue]: Done 👍  Thanks!

File: pages/events/index.vue [hunk 5]
```diff
@@ -31,19 +31,32 @@ import QiskitPage from '~/components/qiskit/QiskitPage.vue'
...
 export default class extends QiskitPage {
   routeName: string = 'events'
+  windowWidth: Number = 0
 
   autoplayVideo () {
+    if (!this.$refs.video) {
+      return
+    }
+
+    const video = this.$refs.video as any
```
[the remark this answers is not in the document]
Comment (marinaaisa) [reply pages/events/index.vue]: Done 👍  Thanks!

**Comment by marinaaisa** [comment]
Hey @delapuente I've just fixed the changes you requested! 👍
